services:
  mysql:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pucaws"
  app:
    build: ../
    ports:
      - 8080:8080
    depends_on:
      - mysql
    restart: on-failure