services:
  mysql:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pucaws"
  app:
    build: ../
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - rabbitmq
    restart: on-failure
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
    hostname: my-rabbit